services:
  echo_agent:
    build: ./agents/echo_agent
    ports:
      - "8001:8000"
      - "9001:9000" # MCP Server port
    environment:
      - MCP_PORT=9000
      - PORT=8000
      - REGISTRY_URL=http://registry_service:8500
    depends_on:
      - redis
      - registry_service

  research_agent:
    build: ./agents/research_agent
    ports:
      - "8002:8000"
      - "9002:9000"
    environment:
      - MCP_PORT=9000
      - PORT=8000
      - REGISTRY_URL=http://registry_service:8500
    depends_on:
      - redis
      - registry_service

  summarize_tool:
    build: ./tools/summarize_text_tool
    ports:
      - "8011:8000"
      - "9011:9000"
    environment:
      - MCP_PORT=9000
      - PORT=8000
      - REGISTRY_URL=http://registry_service:8500
    depends_on:
      - redis
      - registry_service

  registry_service:
    build: ./services/registry_service
    ports:
      - "8500:8500"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"
