[project]
name = "omega"
version = "0.1.0"
description = "O.M.E.G.A."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]",
    "openai>=1.75.0",
    "openai-agents",
    "python-a2a",
    "redis",
]
